Consume API from focus app
ChrispyPeaches/FocusFriends pull request #33
Opened 2024-01-31 21:42 UTC by iggy808

The MAUI app is successfully communicating with the API. No blockers.

2024-02-01 20:16 UTC, ChrispyPeaches requested changes
Other than the one question mentioned, it looks good! Nice work overall!

2024-02-01 20:16 UTC, ChrispyPeaches commented on src/FocusApp/MauiProgram.cs
> +            builder.Services.AddSingleton<APIService>();
I think refit's dependency injection might handle the singleton situation. Was this necessary to get the code to work or would we be able to remove it?

2024-02-01 20:18 UTC, wesleypayton submitted a review, later dismissed
LGTM!!! 💯

2024-02-01 23:02 UTC, ChrispyPeaches approved these changes
Gettin that money

2024-02-02 00:14 UTC, wesleypayton approved these changes
Still good, now better 💯

2024-02-02 00:25 UTC, iggy808 commented
Resolved conflicts, refactored implementation to call api upon page load for:

- TimerPage
- SettingsPage
- ShopPage

This is not an optimal implementation- this only serves to demonstrate the fact the API can communicate with the app in a widely integrated way. 

Note: The API calls work when going from the settings page to the timer page- this proves that the instantiated TimerPage holds on to the API client, and allows for the api client to persist across navigation.

2024-02-02 00:30 UTC, wesleypayton approved these changes
LGTM Part 3

2024-02-02 00:37 UTC, ChrispyPeaches approved these changes
💸💸

2024-02-02 00:37 UTC, merged