Create issue and pull request templates
ChrispyPeaches/FocusFriends pull request #50
Opened 2024-03-17 02:47 UTC by ChrispyPeaches

Fixes #49

## Problem
We need consistent formatting for pull requests and issues

## Solution
Create templates

2024-03-18 14:27 UTC, JohnParks032 requested changes
Made small comment on issue template

2024-03-18 14:27 UTC, JohnParks032 commented on .github/issue_template.md
> +## Solution
Would it make more sense if we didn't have a solution on the issue template? My reasoning is that there's a chance that implementation ends up differently than initially thought.

2024-03-18 14:28 UTC, JohnParks032 commented on .github/issue_template.md
> +## Solution
I realized that this could also be a feature and show us how our idea could've changed/developed.

2024-03-18 19:30 UTC, JohnParks032 approved these changes
LGTM

2024-03-19 16:02 UTC, wesleypayton approved these changes
LGTM 💯

2024-03-19 16:02 UTC, merged