Convert to https
ChrispyPeaches/FocusFriends pull request #63
Opened 2024-03-21 19:32 UTC by wesleypayton

Fixes #54

## Problem
We need the local FocusAPI to be able to deploy under https for a more secure connection. The FocusApp will need changes to accommodate an https connection to the API with a self-signed SSL certificate.

### Definition of Done
- The FocusAPI can be deployed using https without issue
- The FocusApp can communicate with the API while its deployed using https
- The FocusAPI shouldn't have an unsafe connection in the swagger browser window (meaning self-signed certificate is validated)

## Solution
- The unsafe connection was fixed by changing the API's urls to use "localhost" rather than "127.0.0.1," which while functionally the same, does not match the "localhost" name contained in the auto-generated SSL certificate
- A new helper class DevHttpHelperExtensions has been added to setup the HttpClient to handle https connections and self-signed certificates properly in an android dev environment
- In addition, setup was added so that once we have the FocusAPI deployed on a server and accessible remotely, we can configure the URL in FocusApp quickly.

## Documentation
Changes and additions are located here
https://github.com/ChrispyPeaches/FocusFriends/wiki/Consuming-API-from-the-MAUI-Application

## How was this tested?
Tested locally by myself and Chris. Deployed API under https and then launched FocusApp and communicated with API via the shop page.

2024-03-21 19:55 UTC, iggy808 commented
LGTM!

2024-03-21 19:55 UTC, iggy808 submitted a review, later dismissed

2024-03-21 20:32 UTC, ChrispyPeaches requested changes
It looks like the https isn't working on the TEST environment. I think it'd be a good idea for this to be implemented by this story since the point of the HTTPS stuff is for deployment purposes.

I tested this by setting the app  the launch in the Release configuration and changing the API url to the https one (https://test.zenpxl.com:25566)

I committed some changes to see if it would work automatically without manually putting the certificate on Portainer, but I got an error about no certificate being configured/installed.
- These changes on this branch have since been reverted, but are still in the committ history for reference

2024-05-03 01:47 UTC, ChrispyPeaches commented
Closing due to stale PR and likely won't be done before demo

2024-05-03 01:47 UTC, closed without merging